areas:
  - mjukvaru utveckling
  - mekanik
  - logistik
  - projektledning
  - säkerhet

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

