# Filename: default_data.yml
# Author: Pablo Karlsson (Pablo.Karlsson@combitech.se)
#
# Description:
# This file contains default data for autopopulating the database.
# Autopopulation is done using the rake command rake autopopulate

areas:
  - mjukvaru utveckling
  - mekanik
  - databashantering
  - användbarhet
  - logistik
  - projektledning
  - säkerhet
  - konstruktion
  - horisontal integration

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

base_abilities:
  tracks: 
    - name: systemutveckling
      areas: 
      - name: databashantering
        abilities: 
          - sql
      - name: mjukvaru utveckling
        abilities: 
          - programmering
          - testning
          - kravspecning
    - name: logistik
      areas: 
      - name: logistik
        abilities: 
          - Optimeringslära
    - name: systemintegration
      areas: 
      - name: Horisontal integration
        abilities: 
          - Optimeringslära
    - name: mekanik
      areas: 
      - name: konstruktion 
        abilities: 
          - cad

users:
  - email: pablo.karlsson@gmail.com
  - email: niclas.fock@combitech.se
  - email: pernilla.forsell@combitech.se
