# This file contains default data for the database and is loaded into the system by
# caliing `rake migrate` followed by `rake autopopulate`
areas:
  - mjukvaru utveckling
  - mekanik
  - databashantering
  - användbarhet
  - logistik
  - projektledning
  - säkerhet
  - konstruktion
  - horisontal integration

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

base_abilities:
  tracks: 
    - name: systemutveckling
      areas: 
      - name: databashantering
        abilities: 
          - sql
      - name: mjukvaru utveckling
        abilities: 
          - programmering
          - testning
          - kravspecning
    - name: logistik
      areas: 
      - name: logistik
        abilities: 
          - Optimeringslära
    - name: systemintegration
      areas: 
      - name: Horisontal integration
        abilities: 
          - Optimeringslära
    - name: mekanik
      areas: 
      - name: konstruktion 
        abilities: 
          - cad

users:
  - email: Pablo.Karlsson@gmail.com
  - email: Niclas.Fock@combitech.se
  - email: Pernilla.Forsell@combitech.se
