areas:
  - mjukvaru utveckling
  - mekanik
  - databashantering
  - användbarhet
  - logistik
  - projektledning
  - säkerhet

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

base_abilities:
  - track: 
    name: systemutveckling
    areas:
      - name: användbarhet
        abilities: 
          - beräkningskunskap
          - hållfasthetslära
          - konstruktion
      - name: databashantering
        abilities: 
          - Postgres
          - Mysql
          - Sqlite
