areas:
  - mjukvaru utveckling
  - mekanik
  - databashantering
  - användbarhet
  - logistik
  - projektledning
  - säkerhet
  - konstruktion

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

base_abilities:
  tracks: 
    - name: systemutveckling
      areas: 
      - name: databashantering
        abilities: 
          - Postgres
          - Mysql
          - Sqlite
      - name: användbarhet
        abilities: 
          - beräkningskunskap
          - hållfasthetslära
          - konstruktion
    - name: logistik
      areas: 
      - name: logistik
        abilities: 
          - Optimeringslära
