areas:
  - mjukvaru utveckling
  - mekanik
  - databashantering
  - användbarhet
  - logistik
  - projektledning
  - säkerhet
  - konstruktion
  - horisontal integration

tracks:
  - mekanik
  - systemutveckling
  - systemintegration
  - teknikinformation
  - information säkerhet
  - kommunikation
  - logistik 

base_abilities:
  tracks: 
    - name: systemutveckling
      areas: 
      - name: databashantering
        abilities: 
          - sql
      - name: mjukvaru utveckling
        abilities: 
          - programmering
          - testning
    - name: logistik
      areas: 
      - name: logistik
        abilities: 
          - Optimeringslära
    - name: systemintegration
      areas: 
      - name: Horisontal integration
        abilities: 
          - Optimeringslära
    - name: mekanik
      areas: 
      - name: konstruktion 
        abilities: 
          - cad
